export const TASKLISTS_FETCH = 'TASKLISTS_FETCH';
export const TASKLISTS_FETCH_SUCCESS = 'TASKLISTS_FETCH_SUCCESS';
export const TASKLIST_SELECT = 'TASKLIST_SELECT';
export const TASKLIST_CREATE_SUCCESS = 'TASKLIST_CREATE_SUCCESS';

export const TASKLIST_CREATE_FORM_ACTIVATE = 'TASKLIST_CREATE_FORM_ACTIVATE';
export const TASKLIST_CREATE_FORM_CLOSE = 'TASKLIST_CREATE_FORM_CLOSE';
export const TASKLIST_CREATE_FORM_SUBMIT = 'TASKLIST_CREATE_FORM_SUBMIT';
export const TASKLIST_TITLE_CHANGE = 'TASKLIST_TITLE_CHANGE';

export const MESSAGE_SET = 'MESSAGE_SET';