export const USER_VERIFY = 'USER_VERIFY';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_VERIFY_FAILURE = 'USER_VERIFY_SUCCESS_FAILURE';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';

export const TASKLISTS_FETCH = 'TASKLISTS_FETCH';
export const TASKLISTS_FETCH_SUCCESS = 'TASKLISTS_FETCH_SUCCESS';
export const TASKLIST_CREATE_SUCCESS = 'TASKLIST_CREATE_SUCCESS';
export const TASKLIST_UPDATE_SUCCESS = 'TASKLIST_UPDATE_SUCCESS';
export const TASK_COUNT_UPDATE_SUCCESS = 'TASK_COUNT_UPDATE_SUCCESS';

export const TASKLIST_CREATE_FORM_TITLE_CHANGE = 'TASKLIST_CREATE_FORM_TITLE_CHANGE';
export const TASKLIST_CREATE_FORM_SUBMIT = 'TASKLIST_CREATE_FORM_SUBMIT';
export const TASKLIST_CREATE_FORM_SUBMIT_SUCCESS = 'TASKLIST_CREATE_FORM_SUBMIT_SUCCESS';
export const TASKLIST_CREATE_FORM_CLOSE = 'TASKLIST_CREATE_FORM_CLOSE';

export const TASK_IDS_RECEIVE = 'TASK_IDS_RECEIVE';

export const TASKLIST_EDIT_START = 'TASKLIST_EDIT_START';
export const TASKLIST_EDIT_FORM_TITLE_CHANGE = 'TASKLIST_EDIT_FORM_TITLE_CHANGE';
export const TASKLIST_EDIT_FORM_CLOSE = 'TASKLIST_EDIT_FORM_CLOSE';
export const TASKLIST_EDIT_FORM_SUBMIT = 'TASKLIST_EDIT_FORM_SUBMIT';
export const TASKLIST_EDIT_FORM_SUBMIT_COMPLETE = 'TASKLIST_EDIT_FORM_SUBMIT_COMPLETE';

export const TASKLIST_DESTROY = 'TASKLIST_DESTROY';
export const TASKLIST_DESTROY_SUCCESS = 'TASKLIST_DESTROY_SUCCESS';

export const TASKS_FETCH = 'TASKS_FETCH';
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_UPDATE = 'TASK_UPDATE';
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS';
export const TASK_DESTROY = 'TASK_DESTROY';
export const TASK_DESTROY_SUCCESS = 'TASK_DESTROY_SUCCESS';

export const TASK_SORT_UPDATE = 'TASK_SORT_UPDATE';

export const TASK_TITLE_CHANGE = 'TASK_TITLE_CHANGE';
export const TASK_CREATE_FORM_SUBMIT = 'TASK_CREATE_FORM_SUBMIT';
export const TASK_CREATE_FORM_CLEAR = 'TASK_CREATE_FORM_CLEAR';

export const COMPLETED_TASKS_DESTROY = 'COMPLETED_TASKS_DESTROY';
export const COMPLETED_TASKS_DESTROY_SUCCESS = 'COMPLETED_TASKS_DESTROY_SUCCESS';

export const MESSAGE_SET = 'MESSAGE_SET';
